import { Assets, AssetsManifest } from 'pixi.js';

/** List of assets grouped in bundles, for dynamic loading */
/** 按包分组的资源列表，用于动态加载 */
let assetsManifest: AssetsManifest = { bundles: [] };

/** Store bundles already loaded */
/** 存储已加载的包 */
const loadedBundles: string[] = [];

/** Check if a bundle exists in assetManifest  */
/** 检查包是否存在于 assetManifest 中 */
function checkBundleExists(bundle: string) {
    return !!assetsManifest.bundles.find((b) => b.name === bundle);
}

/** Load assets bundles that have nott been loaded yet */
/** 加载尚未加载的资源包 */
export async function loadBundles(bundles: string | string[]) {
    if (typeof bundles === 'string') bundles = [bundles];

    // Check bundles requested if they exists
    // 检查请求的包是否存在
    for (const bundle of bundles) {
        if (!checkBundleExists(bundle)) {
            throw new Error(`[Assets] Invalid bundle: ${bundle}`);
        }
    }

    // Filter out bundles already loaded
    // 过滤掉已经加载的包
    const loadList = bundles.filter((bundle) => !loadedBundles.includes(bundle));

    // Skip if there is no bundle left to be loaded
    // 如果没有剩余的包需要加载，则跳过
    if (!loadList.length) return;

    // Load bundles
    // 加载包
    console.log('[Assets] Load:', loadList.join(', '));
    await Assets.loadBundle(loadList);

    // Append loaded bundles to the loaded list
    // 将已加载的包追加到已加载列表中
    loadedBundles.push(...loadList);
}

/** Check if all bundles are loaded, return false if any of them is not loaded yet  */
/** 检查所有包是否已加载，如果其中任何一个尚未加载则返回 false */
export function areBundlesLoaded(bundles: string[]) {
    for (const name of bundles) {
        // Return false if a single bundle is not present in the loaded list
        // 如果单个包不在已加载列表中，则返回 false
        if (!loadedBundles.includes(name)) {
            return false;
        }
    }

    // All provided bundles are loaded
    // 所有提供的包都已加载
    return true;
}

/** Load the assets json manifest generated by assetpack */
/** 加载由 assetpack 生成的资源 json 清单 */
async function fetchAssetsManifest(url: string) {
    const response = await fetch(url);
    const manifest = await response.json();
    if (!manifest.bundles) {
        throw new Error('[Assets] Invalid assets manifest');
    }
    return manifest;
}

/** Initialise and start background loading of all assets */
/** 初始化并开始后台加载所有资源 */
export async function initAssets() {
    // Load assets manifest
    // 加载资源清单
    assetsManifest = await fetchAssetsManifest('assets/assets-manifest.json');

    // Init PixiJS assets with this asset manifest
    // 使用此资源清单初始化 PixiJS 资源
    await Assets.init({ manifest: assetsManifest, basePath: 'assets' });

    // Load assets for the load screen
    // 为加载界面加载资源
    await loadBundles('preload');

    // List all existing bundles names
    // 列出所有现有包的名称
    const allBundles = assetsManifest.bundles.map((item) => item.name);

    // Start up background loading of all bundles
    // 开始后台加载所有包
    Assets.backgroundLoadBundle(allBundles);
}
